In [1]:
# Importing Libraries

import numpy as np

import pandas as pd

# This version is to merge all the Spell Bee Words - WOC and SOW . Get the unique words to merge to Original Consolidated list

Reading all the spellbee Words from csv files of 2022

In [2]:
SpellBee_2022_WoC_df = pd.read_csv('Bee_Docs/2022_Words Of Champions_Output.csv')
SpellBee_2022_School_df = pd.read_csv('Bee_Docs/2022_School of Words_Output_v1.csv')

Extracting only Words -Year 2022 for Words of champion

In [12]:
SpellBee_2022 =SpellBee_2022_WoC_df[['Difficulty Level','Words']]
SpellBee_2022['WOC_2022'] = 1
SpellBee_2022['SOW_2022'] = 0

In [34]:
SpellBee_2022 = pd.merge(SpellBee_2022,SpellBee_2022_School_df['Words'],how="outer",on=['Words'])

In [35]:
SpellBee_2022['Difficulty Level'].fillna('SOW',inplace=True)
filt = SpellBee_2022.loc[SpellBee_2022['Difficulty Level'] == 'SOW'].index
SpellBee_2022.loc[filt,'WOC_2022'] = 0
SpellBee_2022.loc[filt,'SOW_2022'] = 1
SpellBee_2022.loc[filt]

     Difficulty Level    Words  WOC_2022  SOW_2022
4035              SOW  d’orsay       0.0       1.0

In [36]:
 SpellBee_2022.tail(5)

     Difficulty Level      Words  WOC_2022  SOW_2022
4031            THREE   gallivat       1.0       0.0
4032            THREE  Ner Tamid       1.0       0.0
4033            THREE     Alfvén       1.0       0.0
4034            THREE       Aten       1.0       0.0
4035              SOW    d’orsay       0.0       1.0

In [37]:
 Bee_Output_22 =SpellBee_2022.copy()

In [38]:
SpellBee_2022.to_csv('Bee_Docs/Spell_Bee_2022_merged.csv',encoding='utf-8-sig')

In [39]:
 Bee_Output = pd.read_csv('Bee_Docs/Spell_Bee_Merged_db.csv')

In [40]:
Bee_Output['WOC_2022'] = 0 # Adding new column with default value as 0
Bee_Output = pd.merge( Bee_Output,SpellBee_2022[['Difficulty Level','Words']].dropna(),how="outer",on=['Words','Difficulty Level']) # merging 
Bee_Output.tail(5)

,Unnamed: 0,Difficulty Level,Words,WOC_2021,SOW_2021,WOC_2020,SOW_2020,WOC_2022
5696,NaN,THREE,kyphoplasty,NaN,NaN,NaN,NaN,NaN
5697,NaN,THREE,Ner Tamid,NaN,NaN,NaN,NaN,NaN
5698,NaN,THREE,Alfvén,NaN,NaN,NaN,NaN,NaN
5699,NaN,THREE,Aten,NaN,NaN,NaN,NaN,NaN
5700,NaN,SOW,d’orsay,NaN,NaN,NaN,NaN,NaN

In [41]:
Bee_Output['WOC_2022'].fillna(1,inplace=True) #masking
filt = Bee_Output.loc[Bee_Output['WOC_2022'] == 1].index # filtering the row indexes satisfying the condition
Bee_Output.loc[filt,['SOW_2021','WOC_2021','SOW_2020','WOC_2020']] = 0 # filtering columnns  and updating with zeros
#Bee_Output.loc[filt,'WOC_2020'] = 1 
Bee_Output.loc[filt]

,Unnamed: 0,Difficulty Level,Words,WOC_2021,SOW_2021,WOC_2020,SOW_2020,WOC_2022
4881,NaN,ONE,wide,0.0,0.0,0.0,0.0,1.0
4882,NaN,ONE,last,0.0,0.0,0.0,0.0,1.0
4883,NaN,ONE,sprung,0.0,0.0,0.0,0.0,1.0
4884,NaN,ONE,china,0.0,0.0,0.0,0.0,1.0
4885,NaN,ONE,bonnet,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...
5696,NaN,THREE,kyphoplasty,0.0,0.0,0.0,0.0,1.0
5697,NaN,THREE,Ner Tamid,0.0,0.0,0.0,0.0,1.0
5698,NaN,THREE,Alfvén,0.0,0.0,0.0,0.0,1.0
5699,NaN,THREE,Aten,0.0,0.0,0.0,0.0,1.0
5700,NaN,SOW,d’orsay,0.0,0.0,0.0,0.0,1.0

In [42]:
Bee_Output.drop(['Unnamed: 0'], axis=1,inplace=True)
Bee_Output.head(10)
Bee_Output.to_csv('Bee_Docs/Spell_Bee_All_merged_22year.csv',encoding='utf-8-sig')

In [43]:
Bee_Output['SOW_2022'] = 0
Bee_Output = pd.merge( Bee_Output,SpellBee_2022_School_df['Words'].dropna(),how="outer",on=['Words'])

In [44]:
Bee_Output['Difficulty Level'].fillna('SOW',inplace=True)
filt = Bee_Output.loc[Bee_Output['Difficulty Level'] == 'SOW'].index
Bee_Output.loc[filt,['SOW_2021','WOC_2021','WOC_2022','SOW_2020','WOC_2020']] = 0
Bee_Output.loc[filt,'SOW_2022'] = 1
Bee_Output.loc[filt]

,Difficulty Level,Words,WOC_2021,SOW_2021,WOC_2020,SOW_2020,WOC_2022,SOW_2022
5700,SOW,d’orsay,0.0,0.0,0.0,0.0,0.0,1

In [45]:
Bee_Output.loc[filt,'Difficulty Level'] = 'THREE'
Bee_Output_bkp = Bee_Output.copy()

In [46]:
Bee_Output.to_csv('Bee_Docs/Spell_Bee_All_merged_2022Year.csv',encoding='utf-8-sig')

# Updating SOW/WOC flag based on occurence

In [3]:
SpellBee_All_df = pd.read_csv('Bee_Docs/Spell_Bee_Merged_db.csv')

In [4]:
class Bee():
    def __init__(self,df):
        self.SpellBee_All_df = df
        
    def Flag_Update(self,SpellBee_df, Flag):
        for word in SpellBee_df['Words']:
            filt = self.SpellBee_All_df.loc[self.SpellBee_All_df['Words'] == word ].index
            self.SpellBee_All_df.loc[filt,Flag] =1
            
            

B1=Bee(SpellBee_All_df)
Flag_List = [[SpellBee_2022_School_df,'SOW_2022'],[SpellBee_2022_WoC_df,'WOC_2022']]
for item in Flag_List:
    B1.Flag_Update(item[0],item[1])
Output_Bee_df = B1.SpellBee_All_df
Output_Bee_df.head(10)

,Unnamed: 0,Difficulty Level,Words,WOC_2021,SOW_2021,WOC_2020,SOW_2020,WOC_2022,SOW_2022
0,0,ONE,gel,1.0,1.0,0.0,0.0,0.0,0
1,1,ONE,day,1.0,1.0,0.0,0.0,0.0,0
2,2,ONE,scorch,1.0,1.0,0.0,0.0,0.0,0
3,3,ONE,hear,1.0,1.0,0.0,0.0,0.0,0
4,4,ONE,sizzle,1.0,1.0,0.0,0.0,0.0,0
5,5,ONE,jotted,1.0,1.0,0.0,0.0,0.0,0
6,6,ONE,train,1.0,1.0,0.0,0.0,0.0,0
7,7,ONE,upset,1.0,1.0,0.0,0.0,0.0,0
8,8,ONE,motor,1.0,1.0,0.0,0.0,0.0,0
9,9,ONE,sprint,1.0,1.0,0.0,0.0,0.0,0

In [6]:
#Output_Bee_df.drop(['Unnamed: 0'], axis=1,inplace=True)
Output_Bee_df.tail(10)

,Difficulty Level,Words,WOC_2021,SOW_2021,WOC_2020,SOW_2020,WOC_2022,SOW_2022
5691,THREE,Rayleigh wave,0.0,0.0,0.0,0.0,1.0,0
5692,THREE,kalopanax,0.0,0.0,0.0,0.0,1.0,0
5693,THREE,rond de jambe,0.0,0.0,0.0,0.0,1.0,0
5694,THREE,Gaia,0.0,0.0,0.0,0.0,1.0,0
5695,THREE,derring-do,0.0,0.0,0.0,0.0,1.0,0
5696,THREE,kyphoplasty,0.0,0.0,0.0,0.0,1.0,0
5697,THREE,Ner Tamid,0.0,0.0,0.0,0.0,1.0,0
5698,THREE,Alfvén,0.0,0.0,0.0,0.0,1.0,0
5699,THREE,Aten,0.0,0.0,0.0,0.0,1.0,0
5700,THREE,d’orsay,0.0,0.0,0.0,0.0,0.0,1

In [8]:
Output_Bee_df.to_csv('Bee_Docs/Spell_Bee_Merged_db.csv',encoding='utf-8-sig')